name: DevSecOps CI

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Run Bandit
        run: poetry run bandit -r . || true

      - name: Run Ruff
        run: poetry run ruff check . || true

      - name: Run Safety
        run: poetry run safety check || true